package ui;
//hhhhhhhhhheeeeeeeeeeeeeeeerrrrrrrrrrrrrrrrreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

import ui.LoanForm;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Customer;
import model.Loan;
import service.CustomerService;
import service.LoanService;

public class LoanListForm extends javax.swing.JFrame {

    private LoanService loanService;
    private CustomerService customerService;
    private DefaultTableModel tableModel;
    private Map<Integer, String> customerNames;
    private DashboardForm dashboardForm;

    public LoanListForm() {
        this(null);
    }
    
    public LoanListForm(DashboardForm dashboard) {
        initComponents();
        this.dashboardForm = dashboard;
        loanService = new LoanService();
        customerService = new CustomerService();
        loadCustomerNames();
        setupTable();
        loadLoans();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    private void loadCustomerNames() {
        customerNames = new HashMap<>();
        List<Customer> customers = customerService.getAll();
        for (Customer c : customers) {
            customerNames.put(c.getCustomerId(), c.getFullName());
        }
    }

    private void setupTable() {
        String[] columns = {"Loan ID", "Customer", "Type", "Amount", "Status"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblLoanListForm.setModel(tableModel);
    }

    private void loadLoans() {
        tableModel.setRowCount(0);
        List<Loan> loans = loanService.getAll();
        for (Loan l : loans) {
            String customerName = customerNames.getOrDefault(l.getCustomerId(), "Unknown");
            tableModel.addRow(new Object[]{
                l.getLoanId(),
                customerName,
                l.getLoanType(),
                String.format("%.2f", l.getAmount()),
                l.getStatus()
            });
        }
    }

    private Loan getSelectedLoan() {
        int selectedRow = tblLoanListForm.getSelectedRow();
        if (selectedRow == -1) {
            return null;
        }
        int loanId = (Integer) tableModel.getValueAt(selectedRow, 0);
        List<Loan> loans = loanService.getAll();
        for (Loan l : loans) {
            if (l.getLoanId() == loanId) {
                return l;
            }
        }
        return null;
    }

    public void refreshTable() {
        loadCustomerNames();
        loadLoans();
        // Refresh dashboard statistics if dashboard form is available
        if (dashboardForm != null) {
            dashboardForm.refreshStatistics();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoanListForm = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAddLoan = new javax.swing.JButton();
        btnApproveLoan = new javax.swing.JButton();
        btnRepayLoan = new javax.swing.JButton();
        btnDeleteLoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblLoanListForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLoanListForm);

        btnAddLoan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAddLoan.setText("Add Loan");
        btnAddLoan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnAddLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLoanActionPerformed(evt);
            }
        });

        btnApproveLoan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnApproveLoan.setText("Approve");
        btnApproveLoan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnApproveLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveLoanActionPerformed(evt);
            }
        });

        btnRepayLoan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRepayLoan.setText("Repay");
        btnRepayLoan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnRepayLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepayLoanActionPerformed(evt);
            }
        });

        btnDeleteLoan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDeleteLoan.setText("Delete");
        btnDeleteLoan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnDeleteLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAddLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApproveLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRepayLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApproveLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRepayLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveLoanActionPerformed
        Loan selected = getSelectedLoan();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Please select a loan to approve", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (loanService.approveLoan(selected.getLoanId())) {
            JOptionPane.showMessageDialog(this, "Loan approved successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to approve loan", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnApproveLoanActionPerformed

    private void btnRepayLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepayLoanActionPerformed
        Loan selected = getSelectedLoan();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Please select a loan to repay", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (loanService.repayLoan(selected.getLoanId())) {
            JOptionPane.showMessageDialog(this, "Loan repaid successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to repay loan", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRepayLoanActionPerformed

    private void btnDeleteLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLoanActionPerformed
        Loan selected = getSelectedLoan();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Please select a loan to delete", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this loan?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            if (loanService.deleteLoan(selected.getLoanId())) {
                JOptionPane.showMessageDialog(this, "Loan deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete loan", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteLoanActionPerformed

    private void btnAddLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLoanActionPerformed
        LoanForm loanForm = new LoanForm(this, dashboardForm);
        loanForm.setVisible(true);
    }//GEN-LAST:event_btnAddLoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanListForm().setVisible(true);
            }
        });
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLoan;
    private javax.swing.JButton btnApproveLoan;
    private javax.swing.JButton btnDeleteLoan;
    private javax.swing.JButton btnRepayLoan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLoanListForm;
    // End of variables declaration//GEN-END:variables
}