package ui;

import factory.LoanFactory;
import java.awt.HeadlessException;
import java.util.List;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.JOptionPane;
import model.Customer;
import model.Loan;
import service.CustomerService;
import service.LoanService;
import ui.LoanListForm;

/**
 *
 * @author ykhal
 */
public class LoanForm extends javax.swing.JFrame {

   private proxy.LoanServiceProxy loanService; // Use proxy instead of direct service
    private proxy.CustomerServiceProxy customerService; // Use proxy instead of direct service
    private LoanListForm parentForm;
    private DashboardForm dashboardForm;

    public LoanForm() {
        this(null, null);
    }
    
    public LoanForm(LoanListForm parent) {
        this(parent, null);
    }
    
    public LoanForm(LoanListForm parent, DashboardForm dashboard) {
        initComponents();
        this.parentForm = parent;
        this.dashboardForm = dashboard;
        this.loanService = new proxy.LoanServiceProxy(); // Use proxy
        this.customerService = new proxy.CustomerServiceProxy(); // Use proxy
        setupComboBoxes();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    private void setupComboBoxes() {
        cmbLoanType.removeAllItems();
        cmbLoanType.addItem("Personal");
        cmbLoanType.addItem("Home");
        cmbLoanType.addItem("Car");
        
        cmbCustomer.removeAllItems();
        List<Customer> customers = customerService.getAll();
        for (Customer c : customers) {
            cmbCustomer.addItem(c.getCustomerId() + " - " + c.getFullName());
        }
    }
    
    private void applyForLoan() {
        if (cmbCustomer.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please select a customer", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String customerStr = (String) cmbCustomer.getSelectedItem();
        int customerId = Integer.parseInt(customerStr.split(" - ")[0]);
        String loanType = (String) cmbLoanType.getSelectedItem();
        
        double amount = 0;
        try {
            amount = Double.parseDouble(txtAmount.getText().trim());
            if (amount <= 0) {
                throw new NumberFormatException("Amount must be positive");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid loan amount", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double interestRate = 0;
        try {
            interestRate = Double.parseDouble(txtIntersetRate.getText().trim());
            if (interestRate < 0 || interestRate > 100) {
                throw new NumberFormatException("Interest rate must be between 0 and 100");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid interest rate (0-100)", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int durationMonths = (Integer) spinDuration.getValue();
        
        Loan loan = LoanFactory.createLoan(loanType, customerId, amount, interestRate, durationMonths);
        
        if (loanService.apply(loan)) {
            JOptionPane.showMessageDialog(this, "Loan application submitted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            if (parentForm != null) {
                parentForm.refreshTable();
            }
            if (dashboardForm != null) {
                dashboardForm.refreshStatistics();
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to submit loan application", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCustomer = new javax.swing.JLabel();
        lblLoanType = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblInterestRate = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtIntersetRate = new javax.swing.JTextField();
        cmbCustomer = new javax.swing.JComboBox<>();
        cmbLoanType = new javax.swing.JComboBox<>();
        spinDuration = new javax.swing.JSpinner();
        btnCancel = new javax.swing.JButton();
        btnApplyLoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCustomer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCustomer.setText("customer:");

        lblLoanType.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLoanType.setText("Loan Type:");

        lblAmount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAmount.setText("Amount:");

        lblInterestRate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInterestRate.setText("Interest Rate (%):");

        lblDuration.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDuration.setText("Duration(Months):");

        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtIntersetRate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        cmbCustomer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbLoanType.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbLoanType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        spinDuration.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        spinDuration.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnApplyLoan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnApplyLoan.setText("Apply Loan");
        btnApplyLoan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnApplyLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyLoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInterestRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLoanType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(cmbCustomer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbLoanType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIntersetRate)
                    .addComponent(spinDuration))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(btnApplyLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomer)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoanType)
                    .addComponent(cmbLoanType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIntersetRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInterestRate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuration))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApplyLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void btnApplyLoanActionPerformed(java.awt.event.ActionEvent evt) {
        applyForLoan();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyLoan;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbLoanType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblInterestRate;
    private javax.swing.JLabel lblLoanType;
    private javax.swing.JSpinner spinDuration;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtIntersetRate;
    // End of variables declaration//GEN-END:variables
}