package ui;

import singleton.TransactionManager;
import service.AccountService;
import model.Account;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.Map;
import service.CustomerService;

/**
 *
 * @author ykhal
 */
public class TransactionForm extends javax.swing.JFrame {

    private singleton.TransactionManager transactionManager;
    private proxy.AccountServiceProxy accountService; // Use proxy instead of direct service
    private proxy.CustomerServiceProxy customerService; // Use proxy
    
    /**
     * Creates new form TransactionForm
     */
    public TransactionForm() {
        transactionManager = singleton.TransactionManager.getInstance();
        accountService = new proxy.AccountServiceProxy(); // Use proxy
        customerService = new proxy.CustomerServiceProxy(); // Use proxy
        initComponents();
        setupComboBoxes();
    }
    
    private void setupComboBoxes() {
        try {
            // Setup transaction types
            cmbTransactionType.removeAllItems();
            cmbTransactionType.addItem("Deposit");
            cmbTransactionType.addItem("Withdraw");
            cmbTransactionType.addItem("Transfer");
            
            cmbFromAccount.removeAllItems();
            cmbToAccount.removeAllItems();
            
            List<Account> accounts = accountService.getAll();
            for (Account a : accounts) {
                // Get customer name for this account
                String customerName = "Unknown";
                try {
                    customerName = customerService.getCustomerName(a.getCustomerId());
                } catch (Exception e) {
                    customerName = "Unknown";
                }
                
                String display = a.getAccountId() + " - " + a.getAccountType() + " (" + customerName + ") (Balance: " + String.format("%.2f", a.getBalance()) + ")";
                cmbFromAccount.addItem(display);
                cmbToAccount.addItem(display);
            }
            
            // Add listener for UI updates
            cmbTransactionType.addActionListener(e -> updateUI());
        } catch (Exception e) {
            e.printStackTrace();
            lblTxtMessage.setText("Error loading accounts: " + e.getMessage());
        }
    }

    private void updateUI() {
        String type = (String) cmbTransactionType.getSelectedItem();
        boolean isTransfer = "Transfer".equals(type);
        
        // Enable/disable to account based on transaction type
        cmbToAccount.setEnabled(isTransfer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbFromAccount = new javax.swing.JComboBox<>();
        cmbToAccount = new javax.swing.JComboBox<>();
        cmbTransactionType = new javax.swing.JComboBox<>();
        btnExecute = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblAmmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblTxtMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbFromAccount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbFromAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFromAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFromAccountActionPerformed(evt);
            }
        });

        cmbToAccount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbToAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbToAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbToAccountActionPerformed(evt);
            }
        });

        cmbTransactionType.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbTransactionType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnExecute.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExecute.setText("Execute");
        btnExecute.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblAmmount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAmmount.setText("Ammount");

        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblTxtMessage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTxtMessage.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbFromAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(cmbToAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbTransactionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblTxtMessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFromAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbToAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(cmbTransactionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmmount)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(lblTxtMessage)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {
        if (cmbFromAccount.getSelectedIndex() == -1) {
            lblTxtMessage.setText("Please select source account");
            return;
        }
        
        String fromAccountStr = (String) cmbFromAccount.getSelectedItem();
        int fromAccountId = Integer.parseInt(fromAccountStr.split(" - ")[0]);
        
        String transactionType = (String) cmbTransactionType.getSelectedItem();
        if (transactionType == null) {
            lblTxtMessage.setText("Please select transaction type");
            return;
        }
        
        String amountStr = txtAmount.getText().trim();
        if (amountStr.isEmpty()) {
            lblTxtMessage.setText("Please enter amount");
            return;
        }
        
        double amount;
        try {
            amount = Double.parseDouble(amountStr);
            if (amount <= 0) {
                lblTxtMessage.setText("Amount must be positive");
                return;
            }
        } catch (NumberFormatException e) {
            lblTxtMessage.setText("Invalid amount format");
            return;
        }
        
        boolean success = false;
        String message = "Transaction failed";
        
        if ("Deposit".equals(transactionType)) {
            success = transactionManager.deposit(fromAccountId, amount);
            message = success ? "Deposit successful" : "Deposit failed";
        } else if ("Withdraw".equals(transactionType)) {
            success = transactionManager.withdraw(fromAccountId, amount);
            message = success ? "Withdrawal successful" : "Withdrawal failed (insufficient balance or error)";
        } else if ("Transfer".equals(transactionType)) {
            if (cmbToAccount.getSelectedIndex() == -1) {
                lblTxtMessage.setText("Please select destination account");
                return;
            }
            String toAccountStr = (String) cmbToAccount.getSelectedItem();
            int toAccountId = Integer.parseInt(toAccountStr.split(" - ")[0]);
            
            if (fromAccountId == toAccountId) {
                lblTxtMessage.setText("Cannot transfer to the same account");
                return;
            }
            
            success = transactionManager.transfer(fromAccountId, toAccountId, amount);
            message = success ? "Transfer successful" : "Transfer failed (insufficient balance or error)";
        }
        
        lblTxtMessage.setText(message);
        if (success) {
            // Refresh account lists
            setupComboBoxes();
            txtAmount.setText("");
            
            // Refresh dashboard statistics
            java.awt.Window[] windows = java.awt.Window.getWindows();
            for (java.awt.Window window : windows) {
                if (window instanceof DashboardForm) {
                    ((DashboardForm) window).refreshStatistics();
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnExecuteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbFromAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFromAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFromAccountActionPerformed

    private void cmbToAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbToAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbToAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnExecute;
    private javax.swing.JComboBox<String> cmbFromAccount;
    private javax.swing.JComboBox<String> cmbToAccount;
    private javax.swing.JComboBox<String> cmbTransactionType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAmmount;
    private javax.swing.JLabel lblTxtMessage;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}