package ui;

import service.TransactionService;
import service.AccountService;
import model.Transaction;
import model.Account;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.text.SimpleDateFormat;

/**
 *
 * @author ykhal
 */
public class TransactionListForm extends javax.swing.JFrame {
    
    private proxy.TransactionServiceProxy transactionService; // Use proxy
    private proxy.AccountServiceProxy accountService; // Use proxy
    private proxy.CustomerServiceProxy customerService; // Use proxy
    private Map<Integer, String> accountNames; // Keep this for mapping account IDs
    private boolean isInitializing = true; // Guard to prevent events during initialization

    private DefaultTableModel tableModel;
    
    /**
     * Creates new form TransactionListForm
     */
    public TransactionListForm() {
        transactionService = new proxy.TransactionServiceProxy(); // Use proxy
        accountService = new proxy.AccountServiceProxy(); // Use proxy
        customerService = new proxy.CustomerServiceProxy(); // Use proxy
        accountNames = new HashMap<>(); // Initialize the map
        initComponents();
        setupTable(); // Initialize table model before any operations
        setupAccountFilter();
        isInitializing = false; // Allow events after initialization
        refreshTable();
    }

    private void setupTable() {
        String[] columns = {"Transaction ID", "Account", "Type", "Amount", "Date"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(tableModel);
    }
    
    private void setupAccountFilter() {
        // Remove action listener temporarily to prevent events during initialization
        cmbAccountFilter.removeActionListener(cmbAccountFilter.getActionListeners()[0]);
        
        cmbAccountFilter.removeAllItems();
        cmbAccountFilter.addItem("All Accounts");
        accountNames.clear(); // Clear the map
        
        try {
            List<Account> accounts = accountService.getAll();
            for (Account account : accounts) {
                String customerName = "Unknown";
                
                try {
                    customerName = customerService.getCustomerName(account.getCustomerId());
                } catch (Exception e) {
                    customerName = "Unknown";
                }
                
                String accountDisplay = account.getAccountType() + " - " + account.getAccountId() + " (" + customerName + ")";
                cmbAccountFilter.addItem(accountDisplay);
                accountNames.put(account.getAccountId(), accountDisplay); // Populate the map
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // Re-add the action listener
        cmbAccountFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccountFilterActionPerformed(evt);
            }
        });
    }
    
    private void refreshTable() {
        // Defensive check
        if (tableModel == null) {
            return;
        }
        
        try {
            tableModel.setRowCount(0);
            List<Transaction> transactions = transactionService.getAll();
            
            for (Transaction t : transactions) {
                String accountInfo = accountNames.getOrDefault(t.getAccountId(), "Unknown Account");
                Object[] row = {
                    t.getTransactionId(),
                    accountInfo,
                    t.getTransactionType(),
                    t.getAmount(),
                    t.getTransactionDate()
                };
                tableModel.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading transactions: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblFilterByAccount = new javax.swing.JLabel();
        cmbAccountFilter = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblFilterByAccount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFilterByAccount.setText("Filter By Account:");

        cmbAccountFilter.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbAccountFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Accounts" }));
        cmbAccountFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccountFilterActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFilterByAccount)
                .addGap(30, 30, 30)
                .addComponent(cmbAccountFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilterByAccount)
                    .addComponent(cmbAccountFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed
    
    private void cmbAccountFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccountFilterActionPerformed
        // Prevent action during initialization
        if (isInitializing) {
            return;
        }
        filterTransactions();
    }//GEN-LAST:event_cmbAccountFilterActionPerformed
    
    private void filterTransactions() {
        // Defensive check
        if (tableModel == null) {
            return;
        }
        
        try {
            tableModel.setRowCount(0);
            List<Transaction> transactions;
            
            // Get selected item
            String selectedItem = (String) cmbAccountFilter.getSelectedItem();
            
            if (selectedItem == null || selectedItem.equals("All Accounts")) {
                // Load all transactions
                transactions = transactionService.getAll();
            } else {
                // Extract account ID from the display string "Type - ID (Customer Name)"
                // The format is "Type - ID (Customer Name)"
                String[] parts = selectedItem.split(" - ");
                if (parts.length >= 2) {
                    // Extract the ID part and remove the customer name part in parentheses
                    String idPart = parts[1];
                    String[] idParts = idPart.split(" \\(");
                    if (idParts.length > 0) {
                        int accountId = Integer.parseInt(idParts[0]);
                        transactions = transactionService.getByAccount(accountId);
                    } else {
                        transactions = transactionService.getAll();
                    }
                } else {
                    transactions = transactionService.getAll();
                }
            }
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            
            for (Transaction t : transactions) {
                String accountName = accountNames.getOrDefault(t.getAccountId(), "Unknown Account");
                tableModel.addRow(new Object[]{
                    t.getTransactionId(),
                    accountName,
                    t.getTransactionType(),
                    String.format("%.2f", t.getAmount()),
                    dateFormat.format(t.getTransactionDate())
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error filtering transactions: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbAccountFilter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFilterByAccount;
    // End of variables declaration//GEN-END:variables
}